SELECT BYE.ANIMAL_ID, BYE.NAME FROM ANIMAL_OUTS BYE
LEFT JOIN ANIMAL_INS HI
ON BYE.ANIMAL_ID=HI.ANIMAL_ID
WHERE HI.ANIMAL_ID IS NULL
ORDER BY BYE.ANIMAL_ID, BYE.NAME;


-- NOT IN을 사용한 풀이법
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN
    (
        SELECT ANIMAL_ID
        FROM ANIMAL_INS
    )
ORDER BY ANIMAL_ID;
