SELECT BYE.ANIMAL_ID, BYE.NAME
FROM ANIMAL_INS HI 
JOIN ANIMAL_OUTS BYE ON HI.ANIMAL_ID=BYE.ANIMAL_ID
WHERE BYE.DATETIME-HI.DATETIME>0
ORDER BY BYE.DATETIME-HI.DATETIME DESC
LIMIT 2

-- 다른 정답들
-- DATEDIFF
SELECT I.ANIMAL_ID, I.NAME
from ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.DATETIME IS NOT NULL
ORDER BY DATEDIFF(I.DATETIME, O.DATETIME)
LIMIT 2
