-- 코드를 입력하세요
SELECT HI.ANIMAL_ID, HI.ANIMAL_TYPE, HI.NAME 
FROM ANIMAL_INS HI
JOIN ANIMAL_OUTS BYE
ON HI.ANIMAL_ID=BYE.ANIMAL_ID
WHERE HI.SEX_UPON_INTAKE LIKE '%Intact%'
AND BYE.SEX_UPON_OUTCOME NOT LIKE '%Intact%'
