-- DISTINCT, IS NOT NULL
SELECT COUNT(DISTINCT NAME) 
FROM ANIMAL_INS 
WHERE NAME IS NOT NULL;

-- SUBQUERY, GROUP BY
SELECT COUNT(A.NAME)
FROM (SELECT NAME
FROM ANIMAL_INS
GROUP BY NAME) A

-- GROUP BY를 사용하면 NULL 집계가 안된다.
-- NULL을 따로 집계하고 싶다면
-- CASE WHEN ~ IS NULL THEN 'NULL' ELSE ~ END

-- CASE 
-- WHEN ~ THEN ~ 
-- WHEN ~ THEN ~
-- ...
-- ELSE ~
-- END

-- https://ggmouse.tistory.com/527
