-- 푼 코드
SELECT ANIMAL_ID, NAME, CASE WHEN SEX_UPON_INTAKE LIKE 'Intact%' THEN 'X' ELSE 'O' END AS '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

-- 다른 정답들
-- IF
SELECT ANIMAL_ID, NAME, IF(SEX_UPON_INTAKE LIKE '%Intact%', 'X', 'O') AS '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC;

-- REGEXP (정규표현식)
SELECT 
  ANIMAL_ID,
  NAME,
  (CASE 
    WHEN SEX_UPON_INTAKE REGEXP 'Neutered|Spayed' THEN 'O' ELSE 'X' 
  END) AS 중성화
  FROM ANIMAL_INS
  ORDER BY ANIMAL_ID;
-- https://codingspooning.tistory.com/entry/MySQL-%EC%A0%95%EA%B7%9C%ED%91%9C%ED%98%84%EC%8B%9D-%EA%B2%80%EC%83%89%ED%95%98%EA%B8%B0-REGEXP-LIKE
