-- 코드를 입력하세요
SELECT HOUR(DATETIME), COUNT(DATETIME)
FROM (SELECT DATETIME FROM ANIMAL_OUTS WHERE HOUR(DATETIME) BETWEEN 9 AND 19) A
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)

-- HAVING 이후 조건을 거는 column은 
-- 추가적인 COMMAND가 가미되지 않은 아닌 순수한 column명을 그대로 써줘야한다.