SELECT BYE.ANIMAL_ID, BYE.NAME 
FROM ANIMAL_OUTS BYE
JOIN ANIMAL_INS HI
ON BYE.ANIMAL_ID=HI.ANIMAL_ID
WHERE HI.DATETIME > BYE.DATETIME
ORDER BY HI.DATETIME;

-- JOIN 헷갈리면 확인
-- https://inpa.tistory.com/entry/MYSQL-%F0%9F%93%9A-JOIN-%EC%A1%B0%EC%9D%B8-%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C-%EC%95%8C%EA%B8%B0%EC%89%BD%EA%B2%8C-%EC%A0%95%EB%A6%AC#inner_join_%ED%95%A8%EC%B6%95_%EA%B5%AC%EB%AC%B8
SELECT BYE.ANIMAL_ID, BYE.NAME 
FROM ANIMAL_OUTS BYE, ANIMAL_INS HI
WHERE BYE.ANIMAL_ID=HI.ANIMAL_ID
AND HI.DATETIME > BYE.DATETIME
ORDER BY HI.DATETIME;
